// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXZ966YmrsOO-YNfYSE3ZAHXZeQtseBh4',
    appId: '1:652497796818:web:405e6ef44c98d855def70b',
    messagingSenderId: '652497796818',
    projectId: 'emergency-rapid-response-4e689',
    authDomain: 'emergency-rapid-response-4e689.firebaseapp.com',
    storageBucket: 'emergency-rapid-response-4e689.appspot.com',
    measurementId: 'G-5K3MZ0P5MS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_VF30ezrSGjdeQctMGZdr3Tuup64xCoQ',
    appId: '1:652497796818:android:abb1c3f04c2b357bdef70b',
    messagingSenderId: '652497796818',
    projectId: 'emergency-rapid-response-4e689',
    storageBucket: 'emergency-rapid-response-4e689.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBop7DtSIfYup89syaxuTQcPUJ4hiZOGA8',
    appId: '1:652497796818:ios:9f56189185fdf0ecdef70b',
    messagingSenderId: '652497796818',
    projectId: 'emergency-rapid-response-4e689',
    storageBucket: 'emergency-rapid-response-4e689.appspot.com',
    iosBundleId: 'com.example.lguBplo',
  );
}
